<section class="carousel">
    <div class="diapo" data-speed="5000" data-transition="3000">
        <div class=" elements">
            <div class="element">
                <img src="../assets/img/Carrousel/chef-e.jpg" alt="Gastronomie">
                <div class="caption">
                    <h2>Nous pensons qu’une recette réussie passe d’abord par des produits de qualité</h2>
                </div>
            </div>
            <div class="element">
                <img src="../assets/img/Carrousel/chef.jpg" alt="chef">
                <div class="caption">
                    <h2>Nous pensons qu’une recette réussie passe d’abord par des produits de qualité</h2>
                </div>
            </div>
            <div class="element">
                <img src="../assets/img/Carrousel/chef-i.jpg" alt="dessert">
                <div class="caption">
                    <h2>Nous pensons qu’une recette réussie passe d’abord par des produits de qualité</h2>
                </div>
            </div>
            <div class="element">
                <img src="../assets/img/Carrousel/chef-h.jpg" alt="cuisine">
                <div class="caption">
                    <h2>Nous pensons qu’une recette réussie passe d’abord par des produits de qualité</h2>
                </div>
            </div>
        </div>
        <i class="fa-solid fa-chevron-left"></i>
        <i class="fa-solid fa-chevron-right"></i>
    </div>
</section>
<section class="cards-recipes">
    <div class="recipes">
        <h2>J’ai envie d’une<br>
            <span>Recette…</span>
        </h2>
    </div>
    <div class="cards-elements">
        <div class="element-card">
            <a href="/recipe/index/1">
                <img src="../assets/img/Accueil/img-aperitif.jpg" alt="Apéritif">
                <div class="captions">
                    <h4>Pour</h4>
                    <h1>L’APÉRITIF</h1>
                </div>
            </a>
        </div>
        <div class="element-card">
            <a href="../../recipe/index/2">
                <img src="../assets/img/Accueil/img-entree.jpg" alt="Entrées">
                <div class="captions">
                    <h4>Pour</h4>
                    <h1>UNE ENTRÉE</h1>
                </div>
            </a>
        </div>
        <div class="element-card">
            <a href="../../recipe/index/3">
                <img src="../assets/img/Accueil/img-plat.jpg" alt="Plat">
                <div class="captions">
                    <h4>Pour</h4>
                    <h1>UN PLAT</h1>
                </div>
            </a>
        </div>
        <div class="element-card">
            <a href="../../recipe/index/4">
                <img src="../assets/img/Accueil/img-dessert.jpg" alt="Dessert">
                <div class="captions">
                    <h4>Pour</h4>
                    <h1>UN DESSERT</h1>
                </div>
            </a>
        </div>
    </div>
</section>
<section class="card-cocktail">
    <div class="img-cocktail">
        <img src="../assets/img/Accueil/tout-pour-lapero.jpg" alt="cocktail">
    </div>
    <div class="content-cocktail">
        <div class="title-para">
            <h2>Je veux déguster un <br>
                <span>Cocktail...</span>
            </h2>
            <p>Pour un apéritif convivial et rafraichissant, rien de tel que les cocktails. Avec ou sans alcool, c’est à
                vous de choisir.</p>
        </div>
        <div class="btn-cocktail">
            <a href="/recipe/index/5" type="button">Voir les cocktails</a>
        </div>
    </div>
</section>
<?php require_once '../templates/template_part/_footer.phtml';?>
<script src="../../assets/js/home/carousel.js"></script>