<?php if (!empty($params['message'])): ?>
<div>
  <?= $params['message']?>
</div>
<?php endif ?>
<div class="container">
  <?php if(!empty($params['article'])): ?>
  <h1><?= $params['article']['title']?>
  </h1>
  <article class="card">
    <img src="<?='../../'. $params['article']['file_path_img'] ?>"
      alt="Image d'article<?= $params['article']['title'] ?>">
    <div class="card-content">
      <h2><?= $params['article']['title'] ?></h2>
      <p><?= $params['article']['description'] ?></p>
    </div>
    <div class="card-content">
      <h2>Créer le :</h2>
      <p><?= $params['article']['date_published']; ?></p>
    </div>
    <div class="card-content">
      <h2> Par :</h2>
      <p><?= $params['user'][0]['lastname'] . " " . $params['user'][0]['firstname']; ?></p>
    </div>
  </article>
  <?php endif ?>
</div>