<!DOCTYPE html>
<html lang="fr">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description"
    content="C'est un blog de la gastronomie française qui contient des recettes, des produits finset des livres de recettes">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <script src="https://kit.fontawesome.com/7a969167f1.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="../../assets/css/main.css">
  <!--<link rel="stylesheet" href="../../assets/css/footer.css">
        <link rel="stylesheet" href="../../assets/css/recipe.css">
        <link rel="stylesheet" href="../../assets/css/form.css">
        <link rel="stylesheet" href="../../assets/css/login.css">
        <link rel="stylesheet" href="../../assets/css/table.css">
        <link rel="stylesheet" href="../../assets/css/accueil.css">
        <link rel="stylesheet" href="../../assets/css/modal.css">
        <link rel="stylesheet" href="../../assets/css/contact.css">-->
  <title>home</title>
</head>

<body>
  <header>
    <?php require_once '../templates/template_part/_navbar.phtml';?>
  </header>
  <main class="main-content">

  </main>


</body>


</html>