<footer>
    <div class="footer_container">
        <div class="social">
            <a href="#"><i class="fa-brands fa-instagram"></i></i></a>
            <a href="#"><i class="fa-brands fa-square-snapchat"></i></i></a>
            <a href="#"><i class="fa-brands fa-square-twitter"></i></i></a>
            <a href="#"><i class="fa-brands fa-square-facebook"></i></i></a>
        </div>
        <div class="footer dark-mode">
            <div class="footer_logo">
                <img src="/assets/icons/logo-r.jpg" alt="logo">
            </div>
            <ul class="footer_links">
                <li class="footer_link first"><a href="#">Accueil</a></li>
                <li class="footer_link second"><a href="#">Services</a></li>
                <li class="footer_link third"><a href="#">A propos de nous</a></li>
                <li class="footer_link four"><a href="#">Mentions légales</a></li>
            </ul>
        </div>
        <div class="copyright">
            <p>Gastronomia © 2022</p>
        </div>
    </div>
</footer>
<script src="../../assets/js/header/header.js"></script>