    <?php
    use App\Classes\Core\Service;
    ?>
    <?php if (!empty($params['message'])): ?>
    <div>
      <?= $params['message']?>
    </div>
    <?php endif ?>
    <div class="container">
      <?php if(!empty($params['recipe'])): ?>
      <h1>
        <?= $params['recipe']['title']?></h1>
      <article class="card">
        <img src="<?='../../'. $params['recipe']['file_path_img'] ?>"
          alt="Image de recette-<?= $params['recipe']['title'] ?>">
        <div class="card-content">
          <p><?= $params['recipe']['description']; ?>
          </p>
          <h3>Liste des ingrédients</h3>
          <div class="table">
            <table>
              <thead>
                <tr>
                  <th>Nom</th>
                  <th>Quantité</th>
                  <th>Unité</th>
                  <?php if (Service:: ifUserIsConnected()):?>
                  <th>Action</th>
                  <?php endif ?>
                </tr>
              </thead>
              <tbody>
                <?php foreach($params['recipe']['ingredients'] as $ingredient):?>
                <tr id="<?=$ingredient['id'];?>">
                  <td><?= $ingredient['name_ingredient']; ?></td>
                  <td><?= $ingredient['quantity_ingredient']; ?></td>
                  <td><?= $ingredient['unity_ingredient']; ?></td>
                  <?php  if (Service:: ifUserIsConnected()):?>
                  <td>
                    <button class="btn_update_ingredient" id="btn_update_ingredient" type=" button"><i
                        class="fa-solid fa-pen-to-square"></i></button>
                    <button class="btn_delete_ingredient" id="btn_delete_ingredient" type="button"><i
                        class="fa-solid fa-trash-can"></i></button>
                  </td>
                  <?php endif ?>
                </tr>
                <?php endforeach ?>
              </tbody>
            </table>
          </div>
        </div>
        <div class="card-content">
          <h3>Les Etapes</h3>
          <div class=" table">
            <table>
              <thead>
                <tr>
                  <th>Etape N°</th>
                  <th>Description</th>
                  <?php  if (Service:: ifUserIsConnected()):?>
                  <th>Action</th>
                  <?php endif ?>
                </tr>
              </thead>
              <tbody>
                <?php foreach($params['recipe']['steps'] as $step):?>
                <tr id="<?=$step['id'];?>">
                  <td><?= $step['order_step']; ?></td>
                  <td><?= $step['description_step']; ?></td>
                  <?php  if (Service:: ifUserIsConnected()):?>
                  <td>
                    <button class="btn_update_step" id="btn_update_step" type=" button"><i
                        class="fa-solid fa-pen-to-square"></i></button>
                    <button class="btn_delete_step" id=" btn_delete_step" type="button"><i
                        class="fa-solid fa-trash-can"></i></button>
                  </td>
                  <?php endif ?>
                </tr>
                <?php endforeach ?>
              </tbody>
            </table>
          </div>
        </div>
      </article>
      <?php endif ?>
    </div>
    <!----------------------------- Modal pour modifier un ingrédient--------------------->
    <div id="myModal" class="modal_ingredient">
      <span class="close_modal_ingredient">&times;</span>
      <form method="POST" action="/ingredient/update" class="modal_content_ingredient" enctype="multipart/form-data">
        <div class="container_modal_ingredient">
          <h3>Mise à jour de l'ingredient</h3>
          <div class="footer_ingredient">
            <div>
              <label for="" class="">Nom</label>
              <input type="text" id="id_name_ingredient" name="name_ingredient" value="">
            </div>
            <div>
              <label for="" class="">Quantité</label>
              <input type="text" id="id_quantity_ingredient" name="quantity_ingredient" value="">
            </div>
            <div>
              <label for="" class="">Unité</label>
              <input type="text" id="id_unity_ingredient" name="unity_ingredient" value="">
            </div>
            <div class="modal_btn">
              <input type="hidden" style="width:120px ;" id="id_recipe" name="recipe_id"
                value="<?= $params['recipe']['id']; ?>">
              <input type="hidden" style="width:120px ;" id="id_ingredient" name="id" value="">
              <button type="button" class="btn_cancel_ingredient"> Fermer</button>
              <button type="submit" class="btn_update">Modifier</button>
            </div>
          </div>
        </div>
      </form>
    </div>
    <!-----------------------Modal pour supprimer un ingrédient--------------------->
    <div id="myModal" class="modal_ingredient_delete">
      <span class="close_modal_ingredient_delete">&times;</span>
      <form method="POST" action="/ingredient/delete" class="modal_content" enctype="multipart/form-data">
        <div class="container_modal_delete">
          <h2>Supprimer un ingrédient</h2>
          <h3>Etes vous sûr de supprimer cet ingrédient?</h3>
          <div class="footer_ingredient_delete">
            <input type="hidden" id="id_recipe" name="recipe_id" value="<?= $params['recipe']['id']; ?>">
            <input type="hidden" id="id_ingredient_delete" name="id" value="">
            <button type="button" class="btn_cancel_ingredient_delete"> Fermer</button>
            <button type="submit" class="btn_delete">Supprimer</button>
          </div>
        </div>
      </form>
    </div>
    <!---------------------------------- Modal pour modifier une étape -------------------------------------->
    <div id="myModal" class="modal_step">
      <span class="close_modal_step">&times;</span>
      <form method="POST" action="/step/update" class="modal_content_step" enctype="multipart/form-data">
        <div class="container_modal_step">
          <h3>Mise à jour de l'étape</h3>
          <div class="footer_step">
            <div>
              <label for="" class="">Etape N°</label>
              <input type="text" id="id_nbr_step" name="order_step" value="">
            </div>
            <div>
              <label for="" class="">Description</label>
              <input type="text" id="id_description_step" name="description_step" value="">
            </div>
            <div class="modal_btn">
              <input type="hidden" style="width:120px ;" id="id_recipe" name="recipe_id"
                value="<?= $params['recipe']['id']; ?>">
              <input type="hidden" style="width:120px ;" id="id_step" name="id" value="">
              <button type="button" class="btn_cancel_step"> Fermer</button>
              <button type="submit" class="btn_update">Modifier</button>
            </div>
          </div>
        </div>
      </form>
    </div>
    <!---------------------------Modal pour supprimer une étape--------------------->
    <div id="myModal" class="modal_step_delete">
      <span class="close_modal_step_delete">&times;</span>
      <form method="POST" action="/step/delete" class="modal_content" enctype="multipart/form-data">
        <div class="container_modal_delete">
          <h2>Supprimer une étape</h2>
          <h3>Etes vous sûr de supprimer cette étape?</h3>
          <div class="footer_step_delete">
            <input type="hidden" id="id_recipe" name="recipe_id" value="<?= $params['recipe']['id']; ?>">
            <input type="hidden" id="id_step_delete" name="id" value="">
            <button type="button" class="btn_cancel_step_delete"> Fermer</button>
            <button type="submit" class="btn_delete">Supprimer</button>
          </div>
        </div>
      </form>
    </div>
    <?php require_once '../templates/template_part/_footer.phtml' ;?>
    <script src="../../assets/js/recipe/show.js"></script>