<?php

use App\Classes\Core\Service;

 if (!empty($params['successMsg'])):?>
<div class="successMsg">
  <?= $params['successMsg']; ?>
</div>
<?php endif ?>
<?php  if ((Service::ifUserIsConnected()) && (isset($_SESSION['role']) && $_SESSION['role'] === ROLE_ADMIN)):?>
<h1>Liste des utilisateurs</h1>
<?php
if (!empty($params) && isset($params)):?>
<div class="table">
  <table>
    <thead>
      <tr>
        <th>Prenom</th>
        <th>Nom</th>
        <th>Email</th>
        <th>Rôle</th>
        <th>Etat</th>
        <th>Date de création</th>
        <th>Date de mis à jour</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($params['users'] as $user):?>
      <tr>
        <td><?= $user['lastname'] ?></td>
        <td><?= $user['firstname'] ?></td>
        <td><?= $user['email'] ?></td>
        <td><?= $user['role'] ?></td>
        <td><?= ($user['actif'])? 'Actif': 'Désactivé' ?></td>
        <td><?= $user['created_at'] ?></td>
        <td><?= $user['updated_at'] ?></td>
        <td>
          <a href="/user/update/<?=$user['id']?>" type="button"><i class="fa-solid fa-pen-to-square"></i></a>
          <a type="button" id="myBtn" model="user" class="user_delete" data-user_id="<?= $user['id'];?>"><i
              class="fa-solid fa-trash-can"></i></a>
        </td>
      </tr>
    </tbody>
    <?php endforeach ?>
  </table>
</div>
<?php endif ?>
<?php endif ?>

<?php require_once dirname(__DIR__)."/Users/delete.phtml";?>
<?php require_once '../templates/template_part/_footer.phtml';?>
<script src="../../assets/js/home/modal.js"></script>