<div class="wrapper">
    <form method="POST" action="" enctype="multipart/form-data">
        <div class="dbl-field">
            <div class="field">
                <label for="name">Prenom :</label>
                <input type="text" id="name" name="firstname" placeholder="Entrez votre prenom"
                    value="<?= (empty($params['parametrs']))? $params['user']['firstname'] : $params['parametrs']['firstname'];?>">
                <i class="fas fa-user"></i>
                <?php if (!empty($params['errors']['firstname'])): ?>
                <span class="errors">
                    <?= $params['errors']['firstname']?>
                </span>
                <?php endif ?>
            </div>
            <div class="field">
                <label for="name">Nom :</label><span class="required">*</span>
                <input type="text" name="lastname" placeholder="Entrez votre nom"
                    value="<?php if (!empty($params['user']['lastname'])) echo $params['user']['lastname'];?>">
                <i class="fas fa-user"></i>
                <?php if (!empty($params['errors']['lastname'])): ?>
                <span class="errors">
                    <?= $params['errors']['lastname']?>
                </span>
                <?php endif; ?>
            </div>
        </div>
        <div class="dbl-field">
            <div class="field">
                <label for="name">Email :</label><span class="required">*</span>
                <input type="text" name="email" placeholder="Entrez votre email"
                    value="<?php if (!empty($params['user']['email'])) echo $params['user']['email'];?>">
                <i class="fa-solid fa-envelope"></i>
                <?php if (!empty($params['errors']['email'])): ?>
                <span class="errors">
                    <?= $params['errors']['email']?>
                </span>
                <?php endif ?>
            </div>
            <div class="field">
                <label for="name">Mot de passe :</label><span class="required">*</span>
                <input type="password" name="password" placeholder="Votre mot de passe"
                    value="<?php if (!empty($params['user']['password'])) echo $params['user']['password'];?>">
                <i class="fa-solid fa-key"></i>
                <?php if (!empty($params['errors']['password'])): ?>
                <span class="errors">
                    <?= $params['errors']['password']?>
                </span>
                <?php endif ?>
            </div>
        </div>
        <div class="button-area">
            <button type="submit" class="update">Modifier</button>
            <button type="reset" class="delete">Effacer</button>
        </div>
    </form>
</div>