<!-- Modal -->
<div id="myModal" class="modal">
  <span class="close_modal">&times;</span>
  <form method="POST" action="/recipe/delete" class="modal_content" enctype="multipart/form-data">
    <div class=" container_modal">
      <h1>Supprimer une recette</h1>
      <h3>Etes vous sûr de supprimer cette recette?</h3>
      <div class="footer">
        <input type="hidden" id="recipe_deleted_id" name="recipe_id" value="">
        <button type="button" class="btn_cancel"> Fermer</button>
        <button type="submit" class="btn_delete">Supprimer</button>
      </div>
    </div>
  </form>
</div>